name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-fail }}
    strategy:
      matrix:
        rust: [stable]
        julia: ['1.10', '1.11', 'pre']
        allow-fail: [false]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Julia environment
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia }}

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Run tests
        run: |
          git clone https://github.com/Taaitaaiger/jlrs.git
          cd jlrs
          git checkout ef7ca48578f27d5c7d51b901a71977bdc8700375
          cd ..
          julia -e "import Pkg; Pkg.add(url=\"https://github.com/Taaitaaiger/JlrsCore.jl\", rev=\"5cc78665dcea3a400f10dda831fbf36f66f625a9\")"
          export JLRS_JULIA_DIR="$(dirname $(dirname $(which julia)))"
          export LD_LIBRARY_PATH="${JLRS_JULIA_DIR}/lib:${LD_LIBRARY_PATH}"
          ./generate_tests.py $(readlink -f jlrs/jlrs)
          ./run_tests.sh
